export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const EDIT_PARTICIPANT = 'EDIT_PARTICIPANT';
export const DELETE_PARTICIPANT = 'DELETE_PARTICIPANT';
